Optar/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('siteApp.urls')),
    path('admin', include('company.urls')),
    path('admin/areaVitor/', admin.site.urls),
    path('admin/Empresas/', include('client_Company.urls')),
    path('admin/veiculos/', include('vehicle.urls')),
    path('admin/locacoes/', include('location.urls')),
    path('admin/ganhos/', include('gain.urls')),
    path('admin/relatórios/', include('report.urls')),
    path('admin/gastos/', include('spent.urls')),
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

company/urls.py
from django.urls import path

from . import views

app_name = 'company'
urlpatterns = [
    path('', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile')


]

gain/urls.py
from django.urls import path

from . import views

app_name = 'gains'
urlpatterns = [
    path('<slug:slugParam>/', views.gains, name='gains'),
    path('Todos/<int:id>',
         views.portions, name='allPortions'),
    path('<int:id>', views.portions, name='portions'),
]

location/urls.py
from django.urls import path

from . import views

app_name = 'location'
urlpatterns = [
    path('', views.index),
    path('<slug:slugParam>',  views.locations, name='locations'),
    path('locar/<slug:slugParam>/<str:profileParam>', views.locar, name='locar'),
    path('<int:id>/pdf',  views.gerarContrato, name='pdf'),
    path('Todos/',  views.loc, name='allLocations'),
    path('<slug:slugParam>/', views.locations, name='locations'),
    path('<slug:slugParam>/<int:id>',  views.edit, name='edit'),
    path('Todos/<slug:slugParam>/<int:id>',  views.edit, name='editAll'),
    path('Todas/<slug:slugParam>/<int:id>/remove',
         views.remove, name='removeAll'),
    path('<slug:slugParam>/<int:id>/remove',
         views.remove, name='remove'),
    path('Email/<slug:slugParam>/<int:empresa>/<int:id>',
         views.enviarEmail, name='email'),



]

report/urls.py
from django.urls import path

from . import views

app_name = 'report'
urlpatterns = [
    path('', views.reports, name='all'),
    path('<int:id>/pdf',  views.gerarRelatorioView, name='pdf'),



]

vehicle/urls.py
from django.urls import path
from location import views as LocView

from . import views

app_name = 'vehicle'
urlpatterns = [
    path('', views.index, name='indexVehicle'),
    path('', views.index, name='one'),
    path('cadastroVeiculo/', views.register_vehicle, name='regVehicle'),
    path('<slug:slugParam>', views.edit, name='edit'),
    path('<slug:slugParam>/remove', views.remove, name='remove'),
    path('Veiculos/<slug:slugParam>/remove>', views.remove, name='removeAll'),
    path('profile/<slug:slugParam>', views.profile, name='profile'),
]

templates/BaseItems/BaseGSL.html
{% extends 'BaseItems/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block pesquisa %}
{% include 'includeItems/barraPesquisa.html' %}
{% endblock pesquisa %}



{% block content %}
<div style="margin: 0.8em;" class="scrollBar container-fluid">
    <div class="row">
    
    {% if resultados %}
        <div class="  card card-text adjustmentSucess h6 text-success align-items-center">
            <p>Resultados para: {{ resultados }}</p>
        </div>
        <br>
    {% elif number == 0 %}
        <div class="  card card-text  h6 text-success align-items-center">
            <p>Não há {{tag}} cadastrado</p>
        </div>
        <br>
    {% endif %}

    {% if tabela is None %}
        <div class="  card card-text adjustment h6 text-danger align-items-center">
            <p>Busca Inválida: Não há {{tag}}</p>
        </div>
        <br>
    {% endif %}

    <div class="row">
        <div style="width: 100%; height: 70vh" class="mb-3 overflow-auto card">
          <div class="card-body">
            
            {% block title%}
            {%endblock title%}

            {%block incluir%}
            {%endblock incluir%}
          </div>
          
        </div>
      </div>
    
    <div class="text-center">
   
    {%block botao%}
    {%endblock botao%}

</div>
    </div>
</div>
</div>
{% endblock content %}
{% block  scriptAdd %}
    <script src="{% static '/js/scripts.js' %}"></script>
    <script src="{% static '/js/scripts.js' %}"></script>
    <script >
        {% block funcoes %}
        {% endblock funcoes %}
    </script>
{% endblock scriptAdd %}

templates/BaseItems/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image" href="{% static 'dist/img/icone.png' %}" />
  <title>Optar Locações</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{%static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bootstrap 4 
  <link rel="stylesheet" href="plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
  <!-- iCheck -->
  <link rel="stylesheet" href="{%static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{%static 'plugins/jqvmap/jqvmap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{%static 'dist/css/adminlte.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{%static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{%static 'plugins/daterangepicker/daterangepicker.css' %}">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.min.css' %}">
  <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <script src="{%static 'plugins/jquery/jquery.js' %}"></script>
  <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.min.js" integrity="sha256-lSjKY0/srUM9BE3dPm+c4fBo1dky2v27Gdjm2uoZaL0=" crossorigin="anonymous"></script>

  {%block links%}
  {% endblock links %}
</head>
<body class="hold-transition sidebar-mini layout-fixed">

<div class="wrapper">

  {%block preLoader%}
  {%endblock preLoader%}
  

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand  navbar-dark navbar-teal">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    </ul>

    <!-- Right navbar links -->

    <ul class=" navbar-nav ml-auto">
      {%block pesquisa%}
      {%endblock pesquisa%}

      {%block listar%}
      {%endblock listar%}
      

      <li class="nav-item">
        <a  id="BotaoSair"  class="nav-link">
          <!--Botao Sair-->
          <i class="fa-solid fa-arrow-right-from-bracket"></i>        
        </a>
        
      </li>
     
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar   sidebar-light-teal elevation-4">
    <a href="{%url 'vehicle:one' %}" class="brand-link  navbar-light">
      <img src="{%static 'dist/img/icone.png' %}" alt="Optar Locações" width="80%" class="mt-1 brand-image " style="opacity: 1;">
      <span class=" brand-text "><img src="{%static 'dist/img/textoOptar.png' %}" class="top-3" style="width:60%; top:30px;" alt="Optar Locações"></span>

    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-2 pb-0 mb-2 d-flex">
        <a href="#" class="nav-link ">
          <p>
            
          </p>
        </a>
      </div>

      

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul style="font-size: 1.3em;" class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item menu-open">
            <a href="{%url 'vehicle:one' %}" id="1" class="nav-link">
              <i class="nav-icon fa-solid fa-truck"></i>              
              <p>
                Veículos
              </p>
            </a>
        
          </li>
          
          <li class="nav-item">
            <a href="{%url 'location:allLocations' %}" id="2" class="nav-link">
              <i class="nav-icon fa-solid fa-file-signature"></i>              <p>
                Locações
              </p>
            </a>
          </li>
          
          <li class="nav-item">
            <a href="{% url 'report:all' %}" id="3" class="nav-link">
              <i class="nav-icon fas fa-chart-pie"></i>
              <p>
                Relatórios
              </p>
            </a>
            
          </li>
          
          <li class="nav-item">
            <a href="{%url 'clientCompany:empresas' %}" id="4" class="nav-link">
              <i class="nav-icon fa-solid fa-building"></i>              <p>
                Empresas
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{%url 'company:profile' %}" id="5" class="nav-link">
              <i class="nav-icon fa-solid fa-id-card-clip"></i>
              <p>                
              Perfil
              </p>
            </a>
          </li>
          
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            {%block title%}
            
            {%endblock title%}
          </div><!-- /.col -->
          
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        {%block content%}
        {%endblock content%}
        
      </div>
    </section>
             
    </div>
        <!-- /.row (main row) -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    Optar Locações
    <div class="float-right d-none d-sm-inline-block">
      <b>Versão</b> 1.1.0
    </div>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery UI 1.11.4 -->
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->

<!-- Bootstrap 4 -->
<script src="{%static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- ChartJS -->
<!-- Sparkline -->
<script src="{% static 'plugins/sparklines/sparkline.js' %}"></script>
<!-- JQVMap -->
<script src="{%static 'plugins/jqvmap/jquery.vmap.min.js' %}"></script>
<script src="{%static 'plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{%static 'plugins/jquery-knob/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{% static 'plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'plugins/daterangepicker/daterangepicker.js' %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{%static 'plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<!-- Summernote -->
<script src="{%static 'plugins/summernote/summernote-bs4.min.js'%}"></script>
<!--SweetAlert-->
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>


<!-- overlayScrollbars -->
<script src="{%static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{%static 'dist/js/adminlte.js' %}"></script>

<!-- Bootstrap -->    
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.8.2/chart.min.js" integrity="sha512-zjlf0U0eJmSo1Le4/zcZI51ks5SjuQXkU0yOdsOBubjSmio9iCUp8XPLkEAADZNBdR9crRy3cniZ65LF2w8sRA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->

<script src="{%static 'dist/js/pages/dashboard.js' %}"></script>
<script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<script>
  var ob = document.getElementById("{{active}}");
  ob.classList.add("active");

  
  document.getElementById("BotaoSair").onclick= function(){
      swal({
        title: "Tem certeza que deseja sair?",
        icon: "warning",
        buttons: true,
        dangerMode: true,
      }).then((willDelete) => {
        if (willDelete) {
            window.location="{% url 'company:logout' %}"
        } 
      });
  }
</script>
{%block scriptAdd%}
{%endblock scriptAdd%}
</body>
</html>

templates/BaseItems/baseEdit.html
{% extends 'BaseItems/base.html' %}
{% load crispy_forms_tags%}
{%load static%}

{% block links %}
{% endblock links %}

{% block pesquisa%}

{% endblock pesquisa %}

{% block content%}
   
<div onload="readOnlyFunction()" class="container-fluid">
  <div class="row">
  <!-- left column -->
  <div class="col-md-12">
    <!-- general form elements -->
    <div class="card card-teal">
      <div class="card-header">
        {%block cardTitle%}
        {%endblock cardTitle%}
      </div>
      <!-- /.card-header -->
      <!-- form start -->
      <form method="POST">
        {% csrf_token %}
        <div class="card-body">
          <div class="row">
             {%block formulario%}
             {%endblock formulario%} 
          
        </div>
      </div>
        <!-- /.card-body -->

        <div class="card-footer">
          <button type="button" id="botaoVoltar" class="btn bg-gray">Voltar</button>
          <button type="submit" class="voltar btn bg-lightblue">Editar Campos</button>
        
        </div>
      </form>
    </div>
  </div>
</div>
</div>


{%endblock content%}

{% block  scriptAdd %}
 

      {%block funcoes %}
      {% endblock funcoes%}
       
{% endblock scriptAdd %}

templates/BaseItems/baseTabela.html
{%extends 'BaseItems/base.html'%}



{% block content %}
<!-- /.row -->
    
  {% if resultados %}
      <div style="width:100%;" class=" shadow-sm  card  h6 text-success align-items-center">
        <p class="mt-3">Resultados para: {{ resultados }}</p>
      </div>
  {% elif number == 0 %}
    <div style="width:100%;" class=" shadow-sm  card  h6 text-danger align-items-center">
      <p class="mt-3">Não há {{ tag }}</p>
    </div>
    
  {% endif %}

  {% if tabela is None %}
    <div style="width:100%;" class=" shadow-sm  card  h6 text-danger align-items-center">
      <p class="mt-3">Não há {{ tag }}</p>
    </div>
  {% endif %}
{%if number > 0%}
<div class="m-auto row">
    <div class="col-lg-12">
      <div  style="height: 70Vh;" class="card">
        <div class="card-header bg-teal">
          <div class="row">
        
        <div class=" align-items-center mb-3 col-lg-3">
        {% block cardTitle %}
        {% endblock cardTitle %}
        </div>
        <div class="col-lg-9">
          <div class="card-tools">
            <form method="GET" class="input-group input-group-sm" style="width: 150;">
              {% csrf_token %}
              <input type="input" name="inputSearch" class="form-control float-right" placeholder="Pesquisar {{info}}">

              <div class="input-group-append">
                <button type="submit" name="" class="btn btn-default">
                  <i class="fas fa-search"></i>
                </button>
              </div>           
            </form>            
          </div>
        </div>
      </div>
        {% block botaoAdd %}
        {% endblock botaoAdd %}
        </div>
        <!-- /.card-header -->
        <div class="card-body table-responsive p-0" style="height: 300px;">
          <table class="table table-head-fixed text-nowrap">
            <thead>
              {% block thead %}{% endblock thead %}
            </thead>
            <tbody>
              {% block tbody %}{% endblock tbody %}
            </tbody>
          </table>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
      {%block botao%}
      {%endblock botao%}
    </div>
  </div>
  <!-- /.row -->
{%endif%}
{%endblock content%}

{%block  scriptAdd%}
    
    {%block funcoes%}
    {%endblock funcoes%}

{%endblock scriptAdd%}