Optar/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('siteApp.urls')),
    path('admin', include('company.urls')),
    path('admin/areaVitor/', admin.site.urls),
    path('admin/Empresas/', include('client_Company.urls')),
    path('admin/veiculos/', include('vehicle.urls')),
    path('admin/locacoes/', include('location.urls')),
    path('admin/ganhos/', include('gain.urls')),
    path('admin/relatórios/', include('report.urls')),
    path('admin/gastos/', include('spent.urls')),
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

client_Company/urls.py
from django.urls import path

from client_Company import views

app_name = 'clientCompany'
urlpatterns = [
    path('CadastroEmpresa/<str:id>', views.register_Company, name='register'),
    path('', views.listar, name='empresas'),
    path('Editar/<slug:slugParam>', views.edit, name='edit'),
    path('Remover/<slug:slugParam>', views.remove, name='remove'),

]

gain/urls.py
from django.urls import path

from . import views

app_name = 'gains'
urlpatterns = [
    path('<slug:slugParam>/', views.gains, name='gains'),
    path('Todos/<int:id>',
         views.portions, name='allPortions'),
    path('<int:id>', views.portions, name='portions'),
]

location/urls.py
from django.urls import path

from . import views

app_name = 'location'
urlpatterns = [
    path('', views.index),
    path('<slug:slugParam>',  views.locations, name='locations'),
    path('locar/<slug:slugParam>/<str:profileParam>', views.locar, name='locar'),
    path('<int:id>/pdf',  views.gerarContrato, name='pdf'),
    path('Todos/',  views.loc, name='allLocations'),
    path('<slug:slugParam>/', views.locations, name='locations'),
    path('<slug:slugParam>/<int:id>',  views.edit, name='edit'),
    path('Todos/<slug:slugParam>/<int:id>',  views.edit, name='editAll'),
    path('Todas/<slug:slugParam>/<int:id>/remove',
         views.remove, name='removeAll'),
    path('<slug:slugParam>/<int:id>/remove',
         views.remove, name='remove'),
    path('Email/<slug:slugParam>/<int:empresa>/<int:id>',
         views.enviarEmail, name='email'),



]

vehicle/urls.py
from django.urls import path
from location import views as LocView

from . import views

app_name = 'vehicle'
urlpatterns = [
    path('', views.index, name='indexVehicle'),
    path('', views.index, name='one'),
    path('cadastroVeiculo/', views.register_vehicle, name='regVehicle'),
    path('<slug:slugParam>', views.edit, name='edit'),
    path('<slug:slugParam>/remove', views.remove, name='remove'),
    path('Veiculos/<slug:slugParam>/remove>', views.remove, name='removeAll'),
    path('profile/<slug:slugParam>', views.profile, name='profile'),
]

location/forms.py
import datetime

from django import forms
from django.core.exceptions import ValidationError
from gain.models import Gain
from Optar import settings

from .models import Location


class LocationForm(forms.ModelForm):
    start_location = forms.DateField(label="Inicio", input_formats=settings.DATE_INPUT_FORMATS,
                                     widget=forms.DateInput(format="%d/%m/%Y", attrs={'readOnly': False, 'id': 'startLocationID', 'data-mask': '99/99/9999'}))
    end_location = forms.DateField(label="Fim", required=False, input_formats=settings.DATE_INPUT_FORMATS, widget=forms.HiddenInput())  # noqa

    class Meta:
        model = Location
        fields = '__all__'

        labels = {
            'start_location': 'Inicio',
            'end_location': 'Fim',
            'id_empresa': 'Empresa',
            'monthly_value': 'Valor Mensal',
            'number_months': 'Nº de Meses'
        }

        widgets = {
            'id': forms.HiddenInput(),
            'empresa_name': forms.HiddenInput(),
            'id_vehicle': forms.HiddenInput(),
            'id_empresa': forms.Select(attrs={'placeholder': 'id_empresa', 'class': 'form-control',  'id': 'id_empresa', 'required': 'True'}),  # noqa
            'number_months': forms.NumberInput(attrs={"placeholder": "Numero de meses",  'required': "True"}),
            'monthly_value': forms.NumberInput(attrs={'placeholder': ' Valor Mensal', 'required': 'True'}),  # noqa
            'total_value': forms.HiddenInput(),
            'id_company': forms.HiddenInput(),
            'slug_vehicle': forms.HiddenInput(),
            'status': forms.HiddenInput(),
            'can_remove': forms.HiddenInput(),


        }

    def clean_start_location(self):
        date = self.cleaned_data.get('start_location')
        hoje = datetime.date.today()

        if date < hoje:
            raise ValidationError((
                'Data indisponivel'
            ),
                code='invalid'
            )
        return date

    def clean_number_months(self):
        number = self.cleaned_data.get('number_months')

        if number <= 0:
            raise ValidationError((
                'Não é valido'
            ),
                code='invalid'
            )
        return number


class LocationEditForm(forms.ModelForm):
    start_location = forms.DateField(label="Inicio", required=False,  input_formats=settings.DATE_INPUT_FORMATS,
                                     widget=forms.DateInput(format="%d/%m/%Y", attrs={'name': 'inicio', 'readOnly': False, 'id': 'startLocationID', 'data-mask': '99/99/9999'}))
    end_location = forms.DateField(label="Fim", required=False, input_formats=settings.DATE_INPUT_FORMATS, widget=forms.HiddenInput())  # noqa
    monthly_value = forms.IntegerField(required=False, label="Valor Mensal",  widget=forms.NumberInput(attrs={'readOnly': False, 'id': 'monthID'}))  # noqa

    class Meta:
        model = Location
        fields = '__all__'

        labels = {
            'start_location': 'Inicio',
            'end_location': 'Fim',
            'id_empresa': 'Empresa',
            'number_months': 'Nº de Meses'
        }

        widgets = {
            'id': forms.HiddenInput(),
            'empresa_name': forms.HiddenInput(),
            'id_vehicle': forms.HiddenInput(),
            'id_empresa': forms.Select(attrs={'placeholder': 'id_empresa', 'class': 'form-control', 'id': 'empresaID'}),  # noqa
            'number_months': forms.NumberInput(attrs={"placeholder": "Numero de meses",  'required': "True"}),
            'total_value': forms.HiddenInput(),
            'id_company': forms.    HiddenInput(),
            'status': forms.HiddenInput(),
            'can_remove': forms.HiddenInput(),
        }

    def clean_number_months(self):
        number = self.cleaned_data.get('number_months')

        if number <= 0:
            raise ValidationError((
                'Não é valido'
            ),
                code='invalid'
            )
        return number

location/views.py
import datetime
import io
import smtplib
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from logging import exception
from multiprocessing.connection import Client

from client_Company.models import Client_company
from company.models import Company
from dateutil.relativedelta import relativedelta
from decouple import config
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.db.models import Q
from django.forms import ValidationError
from django.http import FileResponse, HttpResponse
from django.shortcuts import redirect, render
from gain.addGains import addGains, removeGains
from gain.models import Gain
from Optar.settings import BASE_DIR, STATICFILES_DIRS
from reportlab.pdfgen import canvas
from spent.models import Spent
from vehicle.models import Vehicle

from .forms import LocationEditForm, LocationForm
from .gerarPdf import createPdf, gerarObj
from .models import Contract, Location


# Create your views here.
@login_required(login_url='company:login', redirect_field_name='next')
def index(request):
    return render(request, 'locacoes.html')


@login_required(login_url='company:login', redirect_field_name='next')
def locations(request, slugParam):
    vehicle = Vehicle.objects.get(slug=slugParam)
    tabela = Location.objects.filter(id_company=request.user,
                                     id_vehicle=vehicle).order_by('start_location')
    number = Location.objects.filter(id_vehicle=vehicle).count()
    data = None
    tag = "Locações"
    removeTag = 'location:remove'
    editTag = "location:edit"
    portionTag = "gains:portions"
    finished = Location.objects.filter(id_vehicle=vehicle, status=False)

    data = request.GET.get('inputSearch')
    if data:

        if len(data) > 0:
            if data.isdigit():
                tabela = Location.objects.filter(Q(id_company=request.user) & Q(Q(  # noqa
                    Q(total_value__icontains=data) | Q(number_months=int(data)) | Q(id__iexact=data)))).order_by('-start_location')  # noqa
            else:
                tabela = Location.objects.filter(Q(id_company=request.user) & Q(Q(start_location__icontains=data) | Q(end_location__icontains=data) | Q(  # noqa
                    empresa_name__icontains=data))).order_by('-start_location')  # noqa
            if tabela.count() == 0:
                tabela = None
                data = None

    return render(request, 'location/locacoes.html', {'active': 1, 'prev': 'location:locations', 'removeTag': removeTag, 'include': 1, 'portionTag': portionTag, 'editTag': editTag, 'finished': finished, 'tag': tag, 'number': number, 'resultados': data, 'slug': slugParam, 'vehicle': vehicle,  'tabela': tabela})  # noqa


@login_required(login_url='company:login', redirect_field_name='next')
def edit(request, slugParam, id):

    vehicle = Vehicle.objects.get(company_user=request.user, slug=slugParam)
    loc = Location.objects.get(
        id_company=request.user, id_vehicle=vehicle, id=id)

    pagos = Gain.objects.filter(id_location=id, it_paid=True).count()
    locationForm = LocationEditForm(instance=loc)

    if pagos == 0:
        flag = True
    else:
        flag = False

    # Checar se esta na locação individual ou Geral
    if "Todos" in str(request.path):
        prev = 'location:allLocations'
        path = 'location:editAll'
        active = 2
        tag2 = True
    else:
        tag2 = False
        active = 1
        path = 'location:edit'
        prev = 'location:locations'

    anterior = locationForm['number_months'].value()
    last_date = loc.end_location
    current_date = loc.start_location

    if request.POST:

        locationForm = LocationEditForm(request.POST, instance=loc)

        if locationForm.is_valid():

            edit = locationForm.save(commit=False)
            edit.id_vehicle = vehicle
            edit.id_company = request.user

            if pagos == 0:

                if Location.objects.filter(id_company=request.user, id_vehicle=vehicle, start_location__lte=edit.start_location, end_location__gte=edit.start_location).exclude(id=id).exists():  # noqa
                    messages.error(request, 'Data já existe!')
                    return redirect(path, slugParam, id)

            if edit.number_months < pagos:
                messages.error(
                    request, "O numero de meses  precisa ser igual ou maior ao número de meses pagos")
            elif edit.number_months == pagos:
                edit.status = True
                edit.can_remove = False
                edit.can_edit = True
                removeGains(last_date, edit.start_location +
                            relativedelta(months=edit.number_months), edit, request.user)
                edit.save()
                messages.success(request, 'Gasto editado com sucesso')
                return redirect(path, slugParam, id)
            elif edit.number_months > pagos:

                if edit.number_months > anterior:
                    addGains(edit, request.user, pagos)
                elif edit.number_months < anterior:
                    # Adicionar Função para remover
                    removeGains(last_date, edit.start_location +
                                relativedelta(months=edit.number_months), edit, request.user)

                edit.status = True
                edit.can_edit = True
                edit.can_remove = True
                edit.save()

                messages.success(request, 'Gasto editado com sucesso')
                return redirect(path, slugParam, id)

    return render(request, 'location/EditarLocacao.html', {'active': active, 'flag': flag, 'path': path, 'name': 'location', 'tag2': tag2, 'prev': prev, 'name': 'Locação', 'id': id, 'slug': slugParam, 'vehicle': vehicle, 'form': locationForm})


@login_required(login_url='company:login', redirect_field_name='next')
def gerarContrato(request, id):
    location = Location.objects.get(id_company=request.user, id=id)
    contract = Contract.objects.get(id_location=location)

    # Create a file-like buffer to receive PDF data.
    buffer = io.BytesIO()
    # Create the PDF object, using the buffer as its "file."
    p = canvas.Canvas(buffer)
    createPdf(p, contract)
    p.showPage()
    p.save()
    buffer.seek(0)
    return FileResponse(buffer, as_attachment=True, filename='location-'+str(location.id)+'.pdf')


@login_required(login_url='company:login', redirect_field_name='next')
def loc(request):

    vehicle = Vehicle.objects.filter(company_user=request.user)
    tabela = Location.objects.filter(
        id_company=request.user).order_by('-start_location')
    number = Location.objects.filter(id_company=request.user).count()
    data = None
    tag = "Locações"
    removeTag = 'location:removeAll'
    editTag = 'location:editAll'
    portionTag = 'gains:allPortions'
    finished = Location.objects.filter(id_company=request.user, status=False)
    info = "(formato de data yyyy-mm-dd)"

    if request.GET.get('inputSearch'):
        data = request.GET.get('inputSearch')

        if len(data) > 0:
            if data.isdigit():
                tabela = Location.objects.filter(Q(id_company=request.user) & Q(Q(  # noqa
                    Q(total_value__icontains=data) | Q(number_months=int(data)) | Q(id__iexact=data)))).order_by('-start_location')  # noqa
            else:
                tabela = Location.objects.filter(Q(id_company=request.user) & Q(Q(start_location__icontains=data) | Q(end_location__icontains=data) | Q(  # noqa
                    empresa_name__icontains=data))).order_by('-start_location')  # noqa
            if tabela.count() == 0:
                tabela = None
                data = None

    return render(request,  'location/locacoes.html', {'active': 2, 'include': 2, 'prev': 'location:allLocations', 'info': info, 'removeTag': removeTag, 'portionTag': portionTag, 'editTag': editTag, 'finished': finished, 'tag': tag, 'number': number, 'resultados': data, 'slug': None, 'vehicle': vehicle,  'tabela': tabela})


@ login_required(login_url='company:login', redirect_field_name='next')
def remove(request, slugParam, id):

    vehicle = Vehicle.objects.get(company_user=request.user, slug=slugParam)

    remove = Location.objects.get(id_vehicle=vehicle, id=id)

    gains = Gain.objects.filter(id_location=remove, id_vehicle=vehicle, date__range=[
        remove.start_location, remove.end_location], it_paid=False)

    if gains.count() == remove.number_months:
        remove.delete()
        vehicle.it_location = False
        vehicle.save()
    else:
        remove.number_months -= gains.count()
        remove.end_location -= relativedelta(months=gains.count())
        remove.status = True
        remove.can_remove = False
        remove.can_edit = False
        remove.save()

        if datetime.date.today() >= remove.end_location:
            remove.status = False
            remove.save()
            vehicle.it_location = False
            vehicle.save()
    gains.delete()

    if "Todas" in request.path:
        return redirect('location:allLocations')
    else:
        return redirect('location:locations', slugParam)


@ login_required(login_url='company:login', redirect_field_name='next')
def locar(request, slugParam, profileParam):
    vehicle = Vehicle.objects.get(company_user=request.user, slug=slugParam)
    companies = Client_company.objects.filter(company_user=request.user)

    if request.POST:
        form = LocationForm(request.POST)

        if form.is_valid():
            register = form.save(commit=False)
            register.id_vehicle = vehicle
            idEmpresa = request.POST.get('empresas')
            register.id_empresa = Client_company.objects.get(id=idEmpresa)
            register.id_company = request.user
            register.slug_vehicle = vehicle.slug

templates/location/EditarLocacao.html
{% extends 'BaseItems/baseEdit.html' %}
{% load crispy_forms_tags %}
{% load static %}


   
{%block cardTitle%}
<h3 class="card-title">Editar Locação</h3>
{%endblock cardTitle%}

       

{%block formulario%}

<div class="row">          
    {% for field in form.visible_fields  %}
        
    
    <div class="col-md-4">
      {{field|as_crispy_field}}
    </div> 
    
  
    {% endfor %}
</div>
{%endblock formulario%}
            


{%block funcoes %}
<script>
{%if flag is False%}
document.getElementById('startLocationID').readOnly = true;    //to enable readonly
document.getElementById('monthID').readOnly = true;    //to enable readonly

{%else%}   
document.getElementById('startLocationID').readOnly = false;    //to enable readonly
document.getElementById('monthID').readOnly = false;    //to enable readonly

{%endif%}




{% for msg in messages %}
  {% if msg.tags == "message-sucess" %}
  var icon= "success";
  {% elif msg.tags == "message-error" %}
  var icon="error";
  {%endif%}

  swal({
   title: "{{msg}}",
   icon: icon,
   timer: 3000,
   button: "ok"}).then((value) => {
    {% if name == "Gasto"%}
    window.location="{%url 'vehicle:spents' slug %}";
    {% else %}
    window.location="{%url path slug id %}";
    {% endif %}

  });
  {%endfor%}

  document.getElementById('botaoVoltar').onclick= function(){
    
    {%if tag2 is True%}
    window.location="{%url prev %}";
    {%elif tag2 is False or name == "Gasto"%}
    window.location="{%url prev slug %}";
    {%endif%}
  };
</script>
{% endblock funcoes%}
      
    

templates/location/cadastroEmpresa.html
{% extends 'BaseItems/base.html' %}
{% load crispy_forms_tags%}
{%load static%}

{% block links %}
    <link href="{% static 'css/screenChange.css' %}" rel="stylesheet" />
{% endblock links %}

{% block pesquisa%}



    
   
{% endblock %}

{% block opcoes %}
    {%include 'includeItems/VehicleOption.html' %}
{% endblock opcoes %}

{% block content%}
   
<div class="container-fluid">
 
  
    <div class="content">
    <div class="top-1 content-card  card">
      <div class=" card-body ">
        <h5 class="card-header card-header-color text-center mb-4">Cadastrar Nova Empresa</h5>
        <div class=" card-text" >
            <form  method='POST'>
              {% csrf_token %} 
         
              <div class="row">          
                  {% for field in form.visible_fields  %}
                      
                    {% if field is form.number%}
                    <div class="col-md-2">
                    {%elif field is form.zip_code or field is form.district%}
                    <div class="col-md-3">
                    {%else%}
                    <div class="col-md-4">
                    {%endif%}
                    
                        {{field|as_crispy_field}}

                    </div>
                  {% endfor %}
                  <div class="card-footer text-center" >
                    <button id="botaoVoltar" type="button" class="btn btn-secondary" data-dismiss="modal">Voltar</button>
                    <button type="submit" name="CadastrarEmpresa" class=" btn btn-primary">Cadastrar Empresa</button>
                    
                  </div>

                  </form>
             
                </div>
        
                        
            
      </div>
      </div>
    </div>
  </div>
    
   
   

</div>
            


   

{%endblock content%}

{% block  scriptAdd %}
  <script src="{% static '/js/scripts.js' %}"></script>
  <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static '/js/jquery.mask.min.js' %}"></script>
  <script src="{% static '/js/scripts.js' %}"></script>
  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>
  <script>
      {% for msg in messages  %}
      swal({  
       title: "Empresa Cadastrada com Sucesso!!",
       icon: "success",
       timer: 3000,
       button: "ok"}).then((value) => {
        {%if previous is not None%}
        window.location="{% url 'location:locar' previous profile %}"
        {%else%}
        window.location="{%url 'clientCompany:empresas' %}"
        {%endif%}

      });
      {% endfor %}

      document.getElementById('botaoVoltar').onclick= function(){
        swal({
          title: "Tem certeza que deseja retornar?",
          text: "Poderá perder dados ja digitados",
          icon: "warning",
          buttons: true,
          dangerMode: true,
        }).then((willDelete) => {
          if (willDelete) {
              {%if previous != None%}
              window.location="{%url 'location:locar' previous profile %}";
              {%else%}
              window.location="{% url 'clientCompany:empresas'%}"
              {%endif%}
            } else {
            swal({title:"Pode alterar seus dados ", timer:1000});
          }
        });
      };
    </script>
    
    </script>
    
{% endblock scriptAdd %}

templates/location/locacoes.html
{%extends 'BaseItems/baseTabela.html'%}
{%load static%}
{%block links%}

{% endblock links %}

{% block cardTitle %}
    <h3 class="card-title">Locações</h3>
{% endblock cardTitle %}


          
{% block thead %}
    <tr>
        <th>ID</th>
        <th>Inicio</th>
        <th>Fim</th>
        <th>Meses</th>
        <th>Empresa</th>
        <th>Total</th>
        <th><th>
    </tr>
{% endblock thead %}
              
           
{% block tbody %}
{%for i in tabela%}
        <tr>
        <td>{{i.id}}</td>
        <td>{{i.start_location}}</td>
        <td>{{i.end_location}}</td>
        <td>{{i.number_months}} </td>
        <td>{{i.empresa_name}} </td>
        <td><span class="tag tag-success">R$ {{i.total_value}}</span></td>
    
        <td>
        {%if i.can_remove is True and i.id_vehicle%}
        <a  id="areSure" href="{%url  removeTag i.id_vehicle.slug i.id%}" class="areSure btn btn-danger btn-sm" data-toggle="tooltip" data-placement="top" title="Excluir">
            <i class="fa-solid fa-trash-can"></i>
        </a>
        {%else%}
        <a  id="areSure" class=" disabled areSure btn btn-danger btn-sm" data-toggle="tooltip" data-placement="top" title="Excluir">
            <i class="fa-solid fa-trash-can"></i>
        </a>
        {%endif%}
        

        
        {% if i.status is True and i.id_vehicle%}
        <a  href="{%url editTag i.id_vehicle.slug i.id %}" class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="top" title="Editar">
            <i class="fa-solid fa-pen-to-square"></i>
        </a>
    {%else%}
        <a class="disabled btn btn-primary btn-sm" data-toggle="tooltip" data-placement="top" title="Editar">
        <i class="fa-solid fa-pen-to-square"></i>
        </a>
    {%endif%}
    
        <a  href="{%url portionTag i.id%}" class="btn btn-success btn-sm" data-toggle="tooltip" data-placement="top" title="Parcelas">
        <i class="fa-solid fa-dollar-sign"></i>
        </a>
    
    <a   href="{%url 'location:pdf' i.id %} " name="download" value ="{{i.id}}" class="wantPay btn btn-primary btn-sm" data-toggle="tooltip" data-placement="top" title="Baixar Contrato !">
        <i class="fa-solid fa-cloud-arrow-down"></i>                      </a>
    
    {% if i.id_empresa%}
    <a   href="{%url 'location:email' i.slug_vehicle i.id_empresa.id i.id %} " name="email" value ="{{i.id}}" class="wantPay btn btn-warning btn-sm" data-toggle="tooltip" data-placement="top" title="Envia email">
     {%else%}
     <a    name="email" value ="{{i.id}}" class="disabled wantPay btn btn-warning btn-sm" data-toggle="tooltip" data-placement="top" title="Empresa Excluida">
    {%endif%}
        <i class="fa-solid fa-at"></i>                     
    </a>
    </td>
    </tr>
    {%endfor%}
                   
              
{% endblock tbody %}


{%block botao%}
{%if editTag == "location:edit" %}
<button id="voltar" class="voltar btn btn-dark" type='button'>Voltar <i class="fa-solid fa-angle-left"></i></button>
{%endif%}
{%endblock botao%}



{%block funcoes%}
    <script>
        $(document).on('click', '.areSure', function(){
            return confirm("Tem certeza que deseja deletar ?")
        });
    </script>
    <script>
    
    {% for msg in messages%}
    {% if msg.tags == "message-sucess" %}
    var icon="success";
    {% elif msg.tags == "message-error" %}
    var icon="error";
    {%endif%}
    swal({
        title: "{{msg}}",
        icon: icon,
        timer: 3000,
        button: "ok"})
    {% endfor %}

    

    document.getElementById("voltar").onclick= function(){
    {% if prev == "location:locations"%}
        window.location="{% url 'vehicle:profile' slug %}"
    {%else%}
        window.location="{% url 'location:allLocations' %}"
    {%endif%}
    };

    </script>
{%endblock funcoes%}
            

templates/location/locar.html
{% extends 'BaseItems/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block links %}
  <link href="{% static 'css/screenChange.css' %}" rel="stylesheet" />
{% endblock links %}
{% block pesquisa %}{% endblock %}
{% block opcoes %}
  {%include 'includeItems/VehicleOption.html' %}  
{% endblock opcoes %}
{% block content %}
  <div onload="readOnlyFunction();"  class="container-fluid">
    <div class="content">
      <div class=" content-card  card">
        <div class="card-body ">
          <h5 class="card-header bg-teal card-header-color text-center mb-4">
            Locar Veiculo: {{ vehicle.vehicle_type }}, {{ vehicle.year }},  Chassi: {{ vehicle.chassi }}
          </h5>
          <div class="card-text">
            <form method='POST'>
              {% csrf_token %}
              <div class="row">
                {% for field in form.visible_fields  %}
                  <div class="col-md-3">
                    {% if field.label == "Empresa" %}
                    <label for="empresas">Empresas:</label>

                    <select id="empresas" class="form-control" name="empresas">
                      {%for i in companies %}
                        <option value={{i.id}}>{{i}}</option>
                      {%endfor%}
                    </select>
                    {%else%}
                    {{ field|as_crispy_field }}
                    {%endif%}
                    <datalist id="datalistOptions">
                      {% for i in types %}
                        <option value={{i}}>{{i}}
                        </option>
                      {% endfor %}
                    </datalist>
                  </div>
                {% endfor %}
                <div class="card-footer  text-center">
                  <button id="botaoVoltar"
                          type="button"
                          class="btn btn-secondary"
                          data-dismiss="modal">Voltar</button>
                  <button type="submit" name="CadastrarPost" class=" btn btn-primary">Finalizar Locação</button>
                  <a href="{% url 'clientCompany:register' vehicle.id %}"
                     type="submit"
                     class="btn btn-success"
                     data-toggle="tooltip"
                     data-placement="top"
                     title="Cadastrar Nova  Empresa">
                     <i class="fa-solid fa-plus"></i>
                  </a>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}
{% block  scriptAdd %}
 
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>
  <script>
      {% for msg in messages  %}
      swal({
       title: "Veiculo Locado com Sucesso!!",
       icon: "success",
       timer: 3000,
       button: "ok"}).then((value) => {
        window.location="{%url 'vehicle:one'%}";
      });
      {% endfor %}

      function readOnlyFunction(){
        document.getElementById('startLocationID').readOnly = false;    //to enable readonly
      };

      document.getElementById('botaoVoltar').onclick= function(){
        swal({
          title: "Tem certeza que deseja retornar?",
          text: "Poderá perder dados ja digitados",
          icon: "warning",
          buttons: true,
          dangerMode: true,
        }).then((willDelete) => {
          if (willDelete) {
              {% if profile == 'veiculos'%}
              window.location="{%url 'vehicle:one' %}";
              {% else %}
              window.location="{%url 'vehicle:profile' slug%}"
              {% endif %}
          } else {
            swal({title:"Pode alterar seus dados ", timer:1000});
          }
        });
      };
  </script>
{% endblock scriptAdd %}