Optar/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('siteApp.urls')),
    path('admin', include('company.urls')),
    path('admin/areaVitor/', admin.site.urls),
    path('admin/Empresas/', include('client_Company.urls')),
    path('admin/veiculos/', include('vehicle.urls')),
    path('admin/locacoes/', include('location.urls')),
    path('admin/ganhos/', include('gain.urls')),
    path('admin/relatórios/', include('report.urls')),
    path('admin/gastos/', include('spent.urls')),
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gain/urls.py
from django.urls import path

from . import views

app_name = 'gains'
urlpatterns = [
    path('<slug:slugParam>/', views.gains, name='gains'),
    path('Todos/<int:id>',
         views.portions, name='allPortions'),
    path('<int:id>', views.portions, name='portions'),
]

location/urls.py
from django.urls import path

from . import views

app_name = 'location'
urlpatterns = [
    path('', views.index),
    path('<slug:slugParam>',  views.locations, name='locations'),
    path('locar/<slug:slugParam>/<str:profileParam>', views.locar, name='locar'),
    path('<int:id>/pdf',  views.gerarContrato, name='pdf'),
    path('Todos/',  views.loc, name='allLocations'),
    path('<slug:slugParam>/', views.locations, name='locations'),
    path('<slug:slugParam>/<int:id>',  views.edit, name='edit'),
    path('Todos/<slug:slugParam>/<int:id>',  views.edit, name='editAll'),
    path('Todas/<slug:slugParam>/<int:id>/remove',
         views.remove, name='removeAll'),
    path('<slug:slugParam>/<int:id>/remove',
         views.remove, name='remove'),
    path('Email/<slug:slugParam>/<int:empresa>/<int:id>',
         views.enviarEmail, name='email'),



]

spent/urls.py
from django.urls import path
from location import views as LocView

from . import views

app_name = 'spent'
urlpatterns = [
    path('GastoAdicionado/<slug:slugParam>', views.gastoAdd, name='gastoAdd'),
    path('Gastos/<slug:slugParam>/', views.spents, name='spents'),
    path('Gastos/<slug:slugParam>/<int:id>', views.spentEdit, name='spentEdit'),  # noqa
]

vehicle/urls.py
from django.urls import path
from location import views as LocView

from . import views

app_name = 'vehicle'
urlpatterns = [
    path('', views.index, name='indexVehicle'),
    path('', views.index, name='one'),
    path('cadastroVeiculo/', views.register_vehicle, name='regVehicle'),
    path('<slug:slugParam>', views.edit, name='edit'),
    path('<slug:slugParam>/remove', views.remove, name='remove'),
    path('Veiculos/<slug:slugParam>/remove>', views.remove, name='removeAll'),
    path('profile/<slug:slugParam>', views.profile, name='profile'),
]

vehicle/models.py
import datetime
from unittest import defaultTestLoader

from company.models import Company
from django.db import models
from django.utils.text import slugify


def year_choices():
    lista = []
    for i in range(1950, datetime.date.today().year+1):
        lista.append((i, i))
    return lista


def current_year():
    return datetime.date.today().year


YEARS = year_choices()


class Vehicle(models.Model):

    id = models.BigAutoField(primary_key=True)
    vehicle_type = models.CharField(max_length=50)
    year = models.IntegerField(choices=YEARS, default=current_year)
    company_user = models.ForeignKey(
        Company, on_delete=models.SET_NULL, null=True, blank=True)
    vehicle_model = models.CharField(max_length=60)
    brand = models.CharField(max_length=50)
    chassi = models.CharField(unique=True,
                              max_length=21)
    license_plate = models.CharField(max_length=8)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    slug = models.SlugField(blank=True, null=True)
    it_location = models.BooleanField(blank=True, null=True, default=False)

    def __str__(self):
        return self.vehicle_type + '-' + str(self.year) + '' + self.chassi

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = f'{slugify(self.chassi)}'
            self.slug = slug
        self.chassi = self.chassi.upper()
        self.license_plate = self.license_plate.upper()

        return super().save(*args, **kwargs)


class Vehicle_Types (models.Model):

    company_user = models.ForeignKey(
        Company, on_delete=models.SET_NULL, null=True, blank=True)
    types = models.CharField(max_length=50)

    def __str__(self):
        return self.types + '-' + str(self.company_user)

vehicle/forms.py
import datetime
import re

from django import forms
from django.core.exceptions import ValidationError

from .models import Vehicle


def license_Plate_validation(lp):
    regex = re.compile(r"^[A-Z]{3}[-][0-9][0-9A-Z][0-9]{2}$")

    if not regex.match(lp) or len(lp) < 8:
        raise ValidationError((
            'Placa no formato indevido'
        ),
            code='invalid'
        )


class VehicleForm(forms.ModelForm):

    class Meta:
        model = Vehicle
        fields = '__all__'

        labels = {
            'vehicle_type': 'Tipo de Veiculo',
            'year': 'Ano',
            'vehicle_model': 'Modelo',
            'brand': 'Marca',
            'chassi': 'CHASSI',
            'license_plate': 'Placa',
            'it_location': 'it_location'
        }

        help_texts = {
            'chassi': 'Adicione o chassi no padrão correto',
            'license_plate': 'A placa segue o padrão AAA-0000'
        }

        error_messages = {
            'chassi': {
                'required': 'Este campo é obrigatório',
                'invalid': 'Chassi invalido'
            }
        }

        widgets = {
            'it_location': forms.HiddenInput(),
            'vehicle_type': forms.TextInput(attrs={'placeholder': 'Tipo de Veículo', 'name': 'vehicle_type', 'list': 'datalistOptions',
                        'type': '', 'id': 'vehiclesDataList'}),  # noqa
            'year': forms.Select(attrs={'placeholder': 'Ano', 'class': 'form-control'}),  # noqa
            'vehicle_model': forms.TextInput(attrs={'placeholder': 'Modelo do veículo', 'class': 'entrada'}),  # noqa
            'brand': forms.TextInput(attrs={'placeholder': ' Marca', 'class': ''}),  # noqa
            'chassi': forms.TextInput(attrs={'placeholder': 'Chassi', 'class': 'text-uppercase', 'data-mask': '0 AA AAAAAAAA 0 00000', 'minlength': '21'}),  # noqa
            'license_plate': forms.TextInput(attrs={'placeholder': 'Placa do Veículo', 'class': 'text-uppercase', 'data-mask': 'AAA-0A00', 'minlength': '8'}),  # noqa
            'company_user': forms.HiddenInput(),
            'slug': forms.HiddenInput(),

        }

    def clean_year(self):
        year = self.cleaned_data.get('year')

        if len(str(year)) != 4:
            raise ValidationError((
                'Ano indisponivel'
            ),
                code='invalid'
            )
        return year

    def clean_chassi(self):
        chassi = self.cleaned_data.get('chassi')
        regex = re.compile(r"^\d\s\D{2}\s\w{8}\s\d\s\d{5}$")

        if not regex.match(chassi):
            raise ValidationError((
                'Chassi não corresponde ao padrão correto'
            ),
                code='invalid'
            )
        return chassi

vehicle/views.py
import datetime

from client_Company.forms import Client_CompanyForm
from dateutil.relativedelta import relativedelta
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils.text import slugify
from gain.addGains import addGains
from gain.models import Gain
from location.forms import LocationForm
from location.gerarPdf import gerarObj
from location.models import Contract, Location
from Optar import settings as varoptar
from report.models import Report
from spent.forms import SpentForm
from spent.models import Spent

from vehicle.forms import VehicleForm

from .funcoes import calculateNumberMonths
from .models import Vehicle, Vehicle_Types


# Create your views here.
def check_dates(vehicle, request):

    # Checando locações que chegaram ao fim na data corrente
    try:
        for i in vehicle:
            loc = Location.objects.filter(
                id_company=request.user, id_vehicle=i, status=True)
            for j in loc:
                if j.end_location == datetime.date.today():
                    j.status = False
                    j.can_remove = False
                    i.it_location = False
                    j.save()
                    i.save()
    except:
        pass


@login_required(login_url='company:login', redirect_field_name='next')
def index(request):
    vehicle = Vehicle.objects.filter(company_user=request.user)
    check_dates(vehicle, request)
    tabela = Vehicle.objects.filter(
        company_user=request.user).order_by('-created_at')
    number = Vehicle.objects.filter(company_user=request.user).count()
    resultados = None

    if request.GET.get("inputSearch"):
        valida = request.GET.get("inputSearch")
        resultados = valida
        self.license_plate = self.license_plate.upper()

        if len(valida) > 0:
            tabela = Vehicle.objects.filter(Q(company_user=request.user) & Q(Q(vehicle_type__icontains=valida) | Q(vehicle_model__icontains=valida) | Q(  # noqa
                year__icontains=valida) | Q(brand__icontains=valida) | Q(chassi__icontains=valida) | Q(license_plate__icontains=valida))).order_by('-created_at')  # noqa
            if tabela.count() == 0:
                tabela = None
                resultados = None
        else:
            tabela = Vehicle.objects.filter(company_user=request.user)

    profileParam = "veiculos"

    return render(request, "vehicle/veiculos.html", {'active': 1, 'profile': profileParam, 'tabela': tabela, 'resultados': resultados, 'number': number})


@login_required(login_url='company:login', redirect_field_name='next')
def remove(request, slugParam):

    vehicle = Vehicle.objects.get(company_user=request.user, slug=slugParam)
    remove = Vehicle.objects.filter(slug=slugParam)
    if Location.objects.filter(id_vehicle=vehicle, status=True).exists():
        messages.warning(
            request, "Locação Pendente, veículo nao pode ser excluido")
        if "Veiculos" not in request.path:
            return redirect('vehicle:profile', slugParam)
    else:
        remove.delete()
        messages.success(request, "Veiculo removido com sucesso")

    return redirect('vehicle:one')


@login_required(login_url='company:login', redirect_field_name='next')
def profile(request, slugParam):
    vehicle = Vehicle.objects.get(company_user=request.user, slug=slugParam)
    spents = Spent.objects.filter(id_vehicle=vehicle)
    locations = Location.objects.filter(id_vehicle=vehicle)
    gains = Gain.objects.filter(
        id_vehicle=vehicle, date__year=datetime.date.today().year)
    form = VehicleForm(instance=vehicle)
    addSpent = SpentForm()
    profileParam = str(vehicle.license_plate)

    if request.POST:
        form = VehicleForm(request.POST, instance=vehicle)
        if form.is_valid():
            edit = form.save(commit=False)
            edit.company_user = request.user
            edit.slug = f'{slugify(edit.chassi)}'
            edit.save()
            slugParam = edit.slug

            for i in Location.objects.filter(id_vehicle=edit, status=True):
                if Contract.objects.filter(id_location=i).exists():
                    print("Existe locacao")
                    gerarObj(i)
            messages.success(
                request, 'Dados alterados com sucesso com Sucesso')

    return render(request, 'vehicle/vehicleProfile.html', {'active': 1, 'gains': gains, 'locations': locations, 'spents': spents, 'spentForm': addSpent, 'form': form, 'profile': profileParam, 'vehicle': vehicle, 'slug': slugParam})  # noqa


@login_required(login_url='company:login', redirect_field_name='next')
def register_vehicle(request):
    types = Vehicle_Types.objects.filter(company_user=request.user)
    if request.POST:
        form = VehicleForm(request.POST)
        if form.is_valid():
            register = form.save(commit=False)
            types_reg = Vehicle_Types()
            types_reg.company_user = request.user
            types_reg.types = request.POST.get('vehicle_type')
            register.vehicle_type = request.POST.get('vehicle_type')
            register.company_user = request.user
            register.save()
            messages.success(request, 'Veiculo Cadastrado com Sucesso')
            form = VehicleForm()
    else:
        form = VehicleForm()
    return render(request, 'vehicle/cadastroVeiculo.html', {'active': 1, 'form': form, 'types': types})


@ login_required(login_url='company:login', redirect_field_name='next')
def edit(request, slugParam):
    instancia = Vehicle.objects.get(company_user=request.user, slug=slugParam)
    form = VehicleForm(instance=instancia)
    print("USUARIOOO:", request.user)
    user = request.user
    types = Vehicle_Types.objects.filter(company_user=user)

    if request.POST:

        if request.POST.get('voltar'):
            return redirect('vehicle:indexVehicle')

        form = VehicleForm(request.POST, instance=instancia)
        if form.is_valid():
            print('OLÀAAAA')
            edit = form.save(commit=False)
            edit.company_user = request.user
            edit.slug = f'{slugify(edit.chassi)}'
            edit.save()
            slugParam = edit.slug

            # atualizando os contratos de locacoes em andamento
            try:
                for i in Location.objects.filter(id_vehicle=edit, status=True):
                    if Contract.objects.filter(id_location=i).exists():
                        print("Existe locacao")
                        gerarObj(i)
            except:
                pass

            messages.success(
                request, 'Dados alterados com sucesso com Sucesso')
            return redirect('vehicle:edit', edit.slug)
        else:
            print("AFFF")
    return render(request, 'vehicle/edit.html', {'active': 1, 'form': form, 'types': types, 'slug': slugParam})  # noqa

templates/vehicle/cadastroVeiculo.html
{% extends 'BaseItems/base.html' %}
{% load crispy_forms_tags%}
{%load static%}

{% block links %}
    <link href="{% static 'css/screenChange.css' %}" rel="stylesheet" />
{% endblock links %}

{% block pesquisa%}
    
   
{% endblock %}

{% block opcoes %}
<div class="list-group h5 text-left list-group-flush" style="margin-top: 10%;" >
    {%include 'includeItems/VehicleOption.html'%}
   
</div>

{% endblock opcoes %}

{% block content%}
   
<div class="container-fluid  ">
 
  <div class="content">
    <div class=" content-card  card">
      <div class=" card-body ">
        <h5 class="card-header bg-teal card-header-color text-center mb-4"><b>Cadastrar Veículo</b></h5>
        <div class="card-text" >
            <form method='POST'>
              {% csrf_token %}          
              <div class="row">          
                  {% for field in form.visible_fields  %}
                      
                      <div class="col-md-4">

                      {% if field.label == "Tipo de Veiculo" %}
                      
                        <label for="vehiclesDataList" class="form-label">Tipo de Veiculo*</label>
                        <input class="form-control" name="vehicle_type" required list="datalistOptions" id="vehiclesDataList" placeholder="Tipo de veículo">
                        
                        {% if types %}
                        <datalist id="datalistOptions">
                          {% for i in types%}
                          <option value={{i}}>{{i}}</option>
                          {% endfor %}
                        </datalist>
                        {% endif %}
                       

                      {%elif field.label != "it_location"%}
                        {{field|as_crispy_field}}
                    {% endif %}

                    </div>


                      

                  {% endfor %}
              </div>
        
              <div class="card-footer text-center" >
                  <button id="botaoVoltar" type="button" class="btn btn-secondary" data-dismiss="modal">Voltar</button>
                  <button type="submit" name="CadastrarPost" class=" btn btn-primary">Cadastrar</button>
              </div>           
            </form> 
      </div>
      </div>
    </div>
    </div>
   
   

</div>
            


   

{%endblock content%}

{% block  scriptAdd %}
  <script src="{% static '/js/scripts.js' %}"></script>
  <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static '/js/jquery.mask.min.js' %}"></script>
  <script src="{% static '/js/scripts.js' %}"></script>
  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>
  <script>
      {% for msg in messages  %}
      {% if msg.tags == "message-sucess" %}
      swal({
       title: "Veiculo Cadastrado com Sucesso!!",
       icon: "success",
       timer: 3000,
       button: "ok"}).then((value) => {
        window.location="{%url 'vehicle:indexVehicle' %}";
      });
      {% endif %}
      {% endfor %}

      document.getElementById('botaoVoltar').onclick= function(){
        swal({
          title: "Tem certeza que deseja retornar?",
          text: "Poderá perder dados ja digitados",
          icon: "warning",
          buttons: true,
          dangerMode: true,
        }).then((willDelete) => {
          if (willDelete) {
              window.location="{%url 'vehicle:one' %}";
          } else {
            swal({title:"Continue seu cadastro", timer:1000});
          }
        });
      };
    </script>
{% endblock scriptAdd %}

templates/vehicle/vehicleProfile.html
{% extends 'BaseItems/base.html' %}
{%load static%}
{% load crispy_forms_tags %}

{%block addLink%}
  
{%endblock addLink%}



{%block content%}
<div class="row">
    <!-- left column -->
    <div class="col-md-9">
      <!-- general form elements -->
      <div class="card card-teal">
        <div class="card-header">
          <h3 class="card-title">Perfil: {{vehicle.vehicle_type}} - Placa: {{vehicle.license_plate}}</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form method="POST">
          <div class="card-body">
            {% csrf_token %}
              <div class=" row">
                {% for field in form.visible_fields  %}
                  <div class="col-lg-6">
                    {{ field|as_crispy_field }}
                    <datalist id="datalistOptions">
                      {% for i in types %}
                        <option value = {{i}}>{{i }}
                        </option>
                      {% endfor %}
                    </datalist>
                  </div>
                {% endfor %}
              </div>
          </div>
          <!-- /.card-body -->

          <div class="card-footer">
            <button id="botaoVoltar"
                type="button"
                class="btn btn-secondary"
                data-dismiss="modal">Voltar <i class="fa-solid fa-angle-left"></i></button>
            <button type="submit" id="AtualizarPost" name="AtualizarPost" class="btn btn-primary">Atualizar <i class="fa-regular fa-pen-to-square"></i></button>
            <a href="{%url 'vehicle:remove' slug %}" name="removeButton"
                value="{{ vehicle.chassi }}"
                id="removeButton"
                type="button"
                class="areSure btn btn-danger"> 
                Remover <i class="fa-regular fa-trash-can"></i>
            </a>
                {% if vehicle.it_location %}
                    <button type="button" disabled href="" class="btn btn-secondary">Locado!</button>
                {% else %}
                    <a type="button"  href="{%url 'location:locar' slug profile  %}" class="btn btn-success">Locar <i class="fa-regular fa-circle-check"></i></a>
                    {% endif %}
                <button type="button"
                        class="btn btn-warning"
                        data-toggle="modal"
                        data-target="#exampleModalCenter">Add Gasto <i class="fas-regular fa-dollar-sign"></i>
                </button>

        </div>
        </form>
      </div>
    </div>

    <div class="col-md-3">

        <!-- Profile Image -->
        <div style="height: 96%;" class="card card-primary card-outline">
          <div class="card-body box-profile">
            <div class="text-center">
              <img class="profile-user-img img-fluid img-circle"
                   src="{%static 'dist/img/truck.jpg' %}"
                   alt="">
            </div>

            <h3 class="profile-username text-center">{{vehicle.vehicle_type}}</h3>


            <ul class="list-group list-group-unbordered mb-3">
              <li class="list-group-item">
                <a href="{%url 'gains:gains' slug %}" class="btn bg-success btn-block"><i class="pr-2 fa-solid fa-hand-holding-dollar"></i><b>Ganhos</b></a>
            </li>
              <li class="list-group-item">
                <a href="{%url 'spent:spents' slug %}" class="btn bg-warning btn-block"><i class="pr-2 fa-solid fa-comments-dollar"></i><b>Gastos</b></a>
            </li>
              <li class="list-group-item">
                <a href="{%url 'location:locations' slug %}" class="btn bg-lightblue btn-block"><i class="pr-2 fa-solid fa-file-signature"></i><b>Locações</b></a>
            </li>
            </ul>

          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->

</div>
      <!-- /.card -->

<!-- Modal -->

<div class="modal fade"
     id="exampleModalCenter"
     tabindex="-1"
     role="dialog"
     aria-labelledby="exampleModalCenterTitle"
     aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <form name="form2" action="{%url 'spent:gastoAdd' slug %}" method="POST">
        {% csrf_token %}
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Adicionar Gasto</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {{spentForm.visible_fields|crispy}}
      </div>
      
      <div class="modal-footer">
        <button id="fechar" type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
        <button type="submit" name="addGasto" class="btn btn-primary">Cadastrar Gasto</button>
      </div>
    </form>
    </div>
  </div>

  
{%endblock content%}

{% block  scriptAdd %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>

  <script>
      $(document).on('click', '.areSure', function(e){
        var form = document.getElementById("form-this")
        return confirm("Tem certeza que quer deletar ?")
      });
      {% for msg in messages%}
      {% if msg.tags == "message-sucess" %}
      var icon="success";
      {% elif msg.tags == "message-error" %}
      var icon="error"
      {%else%}
      var icon='warning'
      {%endif%}
      swal({
       title: "{{msg}}",
       icon: icon,
       timer: 3000,
       button: "ok"}).then((value) => {
        if (icon =="error" ) {
          $("#exampleModalCenter").modal('show');
          $('#fechar').on('click', function(){

            $('#exampleModalCenter').modal('hide'); 
          
          });

        } else {
        window.location="{%url 'vehicle:profile' slug %}";
        }
      });

      {% endfor %}
      

      document.getElementById('botaoVoltar').onclick= function(){
        swal({
          title: "Tem certeza que deseja retornar?",
          text: "Poderá perder dados ja digitados",
          icon: "warning",
          buttons: true,
          dangerMode: true,
        }).then((willDelete) => {
          if (willDelete) {
              window.location="{%url 'vehicle:one' %}";
          } {% load static %}

        });
      };
  </script>

{% endblock scriptAdd %}

templates/vehicle/vehicleProfile2.html
{% extends 'BaseItems/base.html' %}
{% load crispy_forms_tags %}
{% block links %}
{% endblock links %}


{% block content %}
  <div class="container-fluid">
    <div class="m-4 row">
      <div class="mb-1 col-lg-8">
        <div style="width: 100%; height: 100%;" class="card">
          <div class="card-body ">
            <h5 class="card-header card-header-color text-center mb-4">
              {{ form.vehicle_type.value }}, {{ form.year.value }},  Chassi: {{ form.chassi.value }}
            </h5>
            <form method='POST'>
              {% csrf_token %}
              <div class=" row">
                {% for field in form.visible_fields  %}
                  <div class="col-lg-6">
                    {{ field|as_crispy_field }}
                    <datalist id="datalistOptions">
                      {% for i in types %}
                        <option value = {{i}}>{{i }}
                        </option>
                      {% endfor %}
                    </datalist>
                  </div>
                {% endfor %}
              </div>
              <div class="card-footer text-center">
                <button id="botaoVoltar"
                        type="button"
                        class="btn btn-secondary"
                        data-dismiss="modal">Voltar <i class="fa-solid fa-angle-left"></i></button>
                <button type="submit" id="AtualizarPost" name="AtualizarPost" class="btn btn-primary">Atualizar <i class="fa-regular fa-pen-to-square"></i></button>
                <a href="{%url 'vehicle:remove' slug %}" name="removeButton"
                        value="{{ vehicle.chassi }}"
                        id="removeButton"
                        type="button"
                        class="areSure btn btn-danger">
                  Remover <i class="fa-regular fa-trash-can"></i>
              </a>
                {% if vehicle.it_location %}
                  <button type="button" disabled href="" class="btn btn-secondary">Locado!</button>
                {% else %}
                  <a type="button"  href="{%url 'location:locar' slug profile  %}" class="btn btn-success">Locar <i class="fa-regular fa-circle-check"></i></a>
                  {% endif %}
                <button type="button"
                        class="btn btn-warning"
                        data-toggle="modal"
                        data-target="#exampleModalCenter">Add Gasto <i class="fas-regular fa-dollar-sign"></i></button>
              </div>
            </form>
          </div>
        </div>
      </div>

      <div style:"position:fixed;" class="mb-1  col-lg-4">
        <div class="row">
        <div style="width: 100%; height: 70vh" class="mb-3 overflow-auto card">
          <div class="card-body">
            {% include 'includeItems/carousselCards.html' %}
          </div>
        </div>
      </div>
      <div class="row">
        <div class="card">
          <a style="text-decoration: none; color: #000;" class="text-center"
          href="#meuCarrossel"
          id="ButtonCaroussel"
          role="button"
          data-slide="next">
          próximo 
        </a>  
        </div>
      </div>

      </div>
    </div>
  </div>
</div>
<!-- Modal -->

<div class="modal fade"
     id="exampleModalCenter"
     tabindex="-1"
     role="dialog"
     aria-labelledby="exampleModalCenterTitle"
     aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <form name="form2" action="{%url 'spent:gastoAdd' slug %}" method="POST">
        {% csrf_token %}
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Adicionar Gasto</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {{spentForm.visible_fields|crispy}}
      </div>
      
      <div class="modal-footer">
        <button id="fechar" type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
        <button type="submit" name="addGasto" class="btn btn-primary">Cadastrar</button>
      </div>
    </form>
    </div>
  </div>


</div>


</div>
{% endblock content %}
{% block  scriptAdd %}

  <script>
      $(document).on('click', '.areSure', function(e){
        var form = document.getElementById("form-this")
        return confirm("Tem certeza que quer deletar ?")
      });
      {% for msg in messages%}
      {% if msg.tags == "message-sucess" %}
      var icon="success";
      {% elif msg.tags == "message-error" %}
      var icon="error"
      {%else%}
      var icon='warning'
      {%endif%}
      swal({
       title: "{{msg}}",
       icon: icon,
       timer: 3000,
       button: "ok"}).then((value) => {
        if (icon =="error" ) {
          $("#exampleModalCenter").modal('show');
          $('#fechar').on('click', function(){

            $('#exampleModalCenter').modal('hide'); 
          
          });

        } else {
        window.location="{%url 'vehicle:profile' slug %}";
        }
      });

      {% endfor %}
      

      document.getElementById('botaoVoltar').onclick= function(){
        swal({
          title: "Tem certeza que deseja retornar?",
          text: "Poderá perder dados ja digitados",
          icon: "warning",
          buttons: true,
          dangerMode: true,
        }).then((willDelete) => {
          if (willDelete) {
              window.location="{%url 'vehicle:one' %}";
          } {% load static %}

        });
      };
  </script>

{% endblock scriptAdd %}