Optar/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('siteApp.urls')),
    path('admin', include('company.urls')),
    path('admin/areaVitor/', admin.site.urls),
    path('admin/Empresas/', include('client_Company.urls')),
    path('admin/veiculos/', include('vehicle.urls')),
    path('admin/locacoes/', include('location.urls')),
    path('admin/ganhos/', include('gain.urls')),
    path('admin/relatórios/', include('report.urls')),
    path('admin/gastos/', include('spent.urls')),
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

client_Company/urls.py
from django.urls import path

from client_Company import views

app_name = 'clientCompany'
urlpatterns = [
    path('CadastroEmpresa/<str:id>', views.register_Company, name='register'),
    path('', views.listar, name='empresas'),
    path('Editar/<slug:slugParam>', views.edit, name='edit'),
    path('Remover/<slug:slugParam>', views.remove, name='remove'),

]

gain/urls.py
from django.urls import path

from . import views

app_name = 'gains'
urlpatterns = [
    path('<slug:slugParam>/', views.gains, name='gains'),
    path('Todos/<int:id>',
         views.portions, name='allPortions'),
    path('<int:id>', views.portions, name='portions'),
]

templates/clientes/EditarClientes.html
{% extends 'BaseItems/baseEdit.html' %}
{% load crispy_forms_tags %}
{% load static %}


   
{%block cardTitle%}
<h3 class="card-title">Editar Empresa</h3>
{%endblock cardTitle%}

       

{%block formulario%}

<div class="row">          
    {% for field in form.visible_fields  %}
        
    <div class="col-md-4">
      {{field|as_crispy_field}}
    </div>      
    {% endfor %}
</div>
{%endblock formulario%}
            


{%block funcoes %}
<script>
  document.getElementById('botaoVoltar').onclick= function(){
    window.location="{%url 'clientCompany:empresas' %}";
  };
</script>

<script>

    
  {%if flag is False%}
  document.getElementById('startLocationID').readOnly = true;    //to enable readonly
  {%else%}        
  document.getElementById('startLocationID').readOnly = false;    //to enable readonly
  {%endif%}
  

  {% for msg in messages %}
    {% if msg.tags == "message-sucess" %}
    var icon= "success";
    {% elif msg.tags == "message-error" %}
    var icon="error";
    {%endif%}

    swal({
     title: "{{msg}}",
     icon: icon,
     timer: 3000,
     button: "ok"}).then((value) => {
      {% if name == "Gasto"%}
      window.location="{%url 'vehicle:spents' slug %}";
      {% else %}
      window.location="{%url path slug id %}";
      {% endif %}

    });
    {%endfor%}

    

  </script>

{% endblock funcoes%}
      
    

templates/clientes/empresas.html
{%extends 'BaseItems/baseTabela.html'%}

{%block listar%}
<li class="nav-item">
  <a name="" class="nav-link" href="{%url 'clientCompany:register' -10  %}" data-toggle="tooltip"
  data-placement="top" title="Adicionar Empresa">
      <!--Botao Adicionar empresa-->
      <i class="fa-solid fa-plus"></i>
    </a>
  </li>
{%endblock listar%}

{% block cardTitle %}
    <h3 class="card-title">{{tag}}</h3>
{% endblock cardTitle %}


{% block thead %}
    <tr>
        <th>Nome</th>
        <th>CNPJ</th>
        <th>Email</th>
        <th>Contato</th>
        <th></th>
        <th></th>
    </tr>
{% endblock thead %}
              
           
{% block tbody %}
{%for i in tabela%}
        <tr>
          <td> {{i.name}} </td>
          <td> {{i.cnpj}} </td>
          <td> {{i.email}} </td>
          <td> {{i.contact}} </td>
          <td>
            <a    href="{%url 'clientCompany:remove' i.slug %}" name="remover" value ="{{i.id}}" class="areSure btn btn-danger btn-sm" data-toggle="tooltip" data-placement="top" title="Excluir">
              <i class="fa-solid fa-trash-can"></i>  
            </a>
          </td>
          <td>
            <a href="{%url 'clientCompany:edit' i.slug%}" name="edit" value ="{{i.id}}" class=" btn btn-primary btn-sm" data-toggle="tooltip" data-placement="top" title="Editar">
              <i class="fa-solid fa-pen-to-square"></i>
            </a>
         </td>                    
        
        
        </tr>   
      {%endfor%}

{% endblock tbody %}





{%block funcoes%}
    <script>


  
    
      {% for msg in messages%}
      {% if msg.tags == "message-sucess" %}
      var icon="success";
      {% elif msg.tags == "message-warning" %}
      var icon="warning";
      {%endif%}
      swal({
       title: "{{msg}}",
       icon: icon,
       timer: 3000,
       button: "ok"})
       {%endfor%}

        $(document).on('click', '.areSure', function(e){
          var form = document.getElementById("form-this")
          return confirm("Tem certeza wue deseja deletar ?")
      });
    </script>
{%endblock funcoes%}
            